# vim /usr/local/bin/alertmanager/alertmanager.yml

global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 24h
  receiver: 'email'
receivers:
- name: 'email'
  email_configs:
  - to: mail1@gmail.com,mail2@gmail.com
    from: 'your_mail@gmail.com'
    smarthost: smtp.gmail.com:587
    auth_username: 'your_mail@gmail.com'
    auth_identity: 'your_mail@gmail.com'
    auth_password: '***********'
    send_resolved: true
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
